# -*- coding: utf-8 -*-
"""Normality_test .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oup5CH2o5_HbsG4yWyj3azTJZKidnb4g
"""

##Normality test##
##LMMA-UIS
##Jose Cediel##

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from matplotlib import style
import seaborn as sns

import statsmodels.api as sm
from scipy import stats

plt.style.use('ggplot')

jd = pd.read_csv("N_Data.csv", delimiter = ';')
print(jd)
jd.head(4)

Con = jd["Concentration"]
mu, sigma = stats.norm.fit(Con)
x = np.linspace(min(Con), max(Con), num=100)
y = stats.norm.pdf(x, mu, sigma)
figu, ax = plt.subplots(figsize=(7,4))
ax.plot(x, y, linewidth=2, label='normal')
ax.hist(x=Con, density=True, bins=30, color="red", alpha=0.5)
ax.plot(Con, np.full_like(Con, -0.01), '|k', markeredgewidth=1)
ax.set_title('Concentration distribution')
ax.set_xlabel('Concentration')
ax.set_ylabel('Probability distribution')
ax.legend();


fig, ax = plt.subplots(figsize=(7,4))
sm.qqplot(Con,fit   = True,line  = 'q',alpha = 0.4,lw    = 2,ax    = ax)
ax.set_title('Q-Q plot', fontsize = 10,
             fontweight = "bold")
ax.tick_params(labelsize = 7)

print('Skewness:', stats.skew(Con))
print('Kursotis:', stats.kurtosis(Con))

## Shapiro-Wilk test
shap_t = stats.shapiro(Con)
shap_t