# -*- coding: utf-8 -*-
"""Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tl9ESuWZndFt7RdjxTCHr8Gse-4cEf4a
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

dc = pd.read_csv("")
print(dc)

import matplotlib.pyplot as plt
import seaborn as sns

jd = sns.boxplot(x='', y='', data = , color = 'red')
plt.show()

import scipy.stats as stats
fvalue, pvalue = stats.f_oneway(dc[''], dc[''], dc[''])
print(fvalue, pvalue)

import statsmodels.api as sm
from statsmodels.formula.api import ols

model = ols(' ~ ', data = dc).fit()
anova = sm.stats.anova_lm(model, typ = 2)
anova

"""Jose Cediel"""
